### PR TITLE
Fix listing deployments without statuses

### PR DESCRIPTION
**Pull request by elia**

### CODE REVIEW

**Comment by mikz** [comment]
Looks good! Thanks.

**Comment by elia** [comment]
:+1: 

Out of curiosity, did you try proposing to merge this repo into the upstream one in the @capistrano org?

**Comment by mikz** [comment]
@elia I did not, there are no merged pull requests for more than a year. Guess I could create an issue and ask the @capistrano maintainers.

**Comment by elia** [comment]
@mikz yes, maybe a (new) maintainer is something they'd like to have :)

**Pull request merged**
