### PR TITLE
Show last deployment

### PR DESCRIPTION
**Pull request by elia**
Show last deployment without loading all states for all deployments

### CODE REVIEW

**Comment by mikz** [comment]
So this does two things:
- lazy load `Deployment#statuses` on access
- add `github:last_deploy` to print information about the last deploy (without the statuses)

right?

It would be nicer, to have those two changes as separate commits, but it is ok this way.
I just enabled travis build, could you rebase it on master to see if it is green? I'll merge it right after.

**Comment by elia** [comment]
:+1:

**Comment by elia** [comment]
green light :vertical_traffic_light:

**Comment by mikz** [comment]
Thank you!

**Pull request merged**
